### ISSUE TITLE
Add page down behavior to spacebar + switch j and k

### ISSUE THREAD

**Issue by rescene** [syndicodefront/infekt#111]
It's handy to use the J and K keybindings to scroll through a directory of nfo files. They are similar to the vi movement key bindings. See http://vimdoc.sourceforge.net/htmldoc/usr_02.html#hjkl

The NFO files do not always fit on your screen. I want to scroll down to see the rest of it. As far as I know, this can only be done with mouse dragging/clicking, scrolling or the page up/down keys.
This doesn't work well in combination with the J and K keys.

I suggest adding the page down behavior to the space bar. Web browsers behave the same.

A folder with nfo files looks like this:
- `a.nfo`
- `b.nfo`
- `c.nfo`

I open the first one (a.nfo). I want to see the next one (b.nfo): go downwards in the Windows explorer list. The vi downwards movement key is j. Upon pressing j, iNFekt show the previous/upwards file (c.nfo). This is not the correct behavior I'm expecting from j and k keys.

J should be _Next NFO_ while K should be _Previous NFO_.

**Comment by flakes** [comment]
The space key makes sense, going to add that.

Swapping J and K keys however does _not_ make sense to me - the order of the keys on a typical western keyboard from left to right is J K. Leftwards motion is commonly associated with going back and rightwards with going forward (e.g. browser buttons). Therefore J K makes perfect sense to me. Dunno what vi guys have been smoking :)

**Comment by Gfyj** [comment]
Here's the history behind the keys:
http://www.catonmat.net/blog/why-vim-uses-hjkl-as-arrow-keys/

> HJKL keys are still ubiquitous in newly developed Unix software even though today's keyboards have arrow keys. [...] Gmail, Google labs' keyboard shortcuts and other websites use J and K for "next" and "previous".

https://en.wikipedia.org/wiki/Arrow_keys#HJKL_keys

Feedly (online RSS aggregator) and DuckDuckGo (search engine) are 2 others I know behave like that.

You compare with left and right, but the mental model is actually up and down. At least for me it was because I was viewing a vertical windows explorer file list. It's very weird to have the behavior switched compared to everything else around using those keys ;) It fails https://en.wikipedia.org/wiki/Principle_of_least_astonishment

How about a setting, if it still doesn't make sense to you?

**Comment by flakes** [comment]
Alright, must be true if it's on Wikipedia ;) Going to change it for the next release.

**Comment by flakes** [comment]
This will be implemented in the next release.
