### ISSUE TITLE
Add support for old school VGA font

### ISSUE THREAD

**Issue by Keith94** [syndicodefront/infekt#115]
There's a browser extension called [**RetroTxt**](https://github.com/bengarrett/RetroTxt) for viewing NFO files, in the options it states that "VGA 8 is the recommended font for viewing ASCII art". I think the VGA font looks nicer compared to iNFekt's Lucida Console and others... can it be added as an option maybe? Other options like font shadows/scan lines seem like a nice addition too.

![firefox_2016-12-02_01-45-15](https://cloud.githubusercontent.com/assets/5490615/20829463/ff9bdc5c-b830-11e6-9af3-13b76235baf5.png)

![firefox_2016-12-02_04-23-21](https://cloud.githubusercontent.com/assets/5490615/20834006/7be13bfc-b847-11e6-86e1-44373edf1467.png)

**Comment by flakes** [comment]
That's nice.png, going to look into it.

**Comment by Keith94** [comment]
Awesome to hear, thank you. :)

**Comment by flakes** [comment]
Do you maybe have screenshots that illustrate the shadows and scanlines features? Because I can't see any difference on my setup (Chrome browser)...

**Comment by Keith94** [comment]
Yes, the differences are more visible with some of the themes/color pairs. I made some comparisons below. First is Amiga theme, second is Windows theme.

Font shadows off
![firefox_2016-12-10_05-40-41](https://cloud.githubusercontent.com/assets/5490615/21073739/f6652f8c-be9b-11e6-80b0-03c13fa30a69.png)

Font shadows on
![firefox_2016-12-10_05-40-51](https://cloud.githubusercontent.com/assets/5490615/21073741/fc3b6bce-be9b-11e6-805d-97e7f9ceed08.png)

Background scan lines off
![firefox_2016-12-10_05-37-41](https://cloud.githubusercontent.com/assets/5490615/21073749/2273f4fa-be9c-11e6-977d-0a200740ba47.png)

Background scan lines on
![firefox_2016-12-10_05-43-16](https://cloud.githubusercontent.com/assets/5490615/21073751/266c0872-be9c-11e6-8caa-922119a9bd58.png)

**Comment by Hackerpcs** [comment]
You can get the result by using the PxPlus IBM VGA8, 16px, Classic from here (CC BY-SA 4.0)

https://int10h.org/oldschool-pc-fonts/fontlist/


![classic](https://user-images.githubusercontent.com/17467335/38032087-6cfca502-32a5-11e8-88a4-1cac166870dd.png)

Rendered has a small glitch, that's why I use classic over rendered

![rendered](https://user-images.githubusercontent.com/17467335/38032123-867b53ac-32a5-11e8-8466-6b2319cdee9f.png)

[Example nfo used](https://defacto2.net/f/ae2f6d6)
[My zenburn styled config](https://pastebin.com/iD7Faa77)

**Comment by Keith94** [comment]
@Hackerpcs Thanks for that! It's a good result.

**Comment by flakes** [comment]
Support for custom fonts will be added with issue #133. Closing this one.
