### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by huubert** [syndicodefront/infekt#134]
Hi,

I think tabs should be interpreted as 4 spaces, and not 8 spaces, as it currently is, to avoid alignment problems, such as this: https://i.imgur.com/txvHA1V.png

**Comment by rescene** [comment]
The default for tabs is 8 spaces. See https://en.wikipedia.org/wiki/Tab_key
The code viewers on Github and Bitbucket also use 8 spaces for the tab indentation.

On [srrDB ](https://bitbucket.org/Skalman/srrdb/issues/95/nfo-viewer-tab-char-is-8-spaces)I switched it from 4 to 8 to have a proper alignment for the art.
An example: https://www.srrdb.com/release/details/(2000_canaries)-sunseeker_(get_up_and_party)_vinyl_techy-bmi
I haven't noticed a badly aligned art since.

**Comment by huubert** [comment]
An example: https://www.srrdb.com/download/file/Barry.Lyndon.1975.REMASTERED.1080p.BluRay.X264-AMIABLE
If you open the nfo with Notepad++ you will notice that all the text is aligned, while it isn't with iNFekt.
However, I suppose there's no way to fix both cases.

**Comment by rescene** [comment]
Looks like the group is not able to make a proper nfo ;)
Open the file with Notepad and you'll notice it behaves the same as iNFekt.
