### ISSUE TITLE
Congratulations on the new version )

### ISSUE THREAD

**Issue by wvxwxvw** [syndicodefront/infekt#144]
Windows 7 x64 sp1 with all updates
Microsoft Visual C++ installed
![2022 02 14_125026](https://user-images.githubusercontent.com/13194155/153840723-cc052cfe-cd84-408f-bf43-31554e96adce.png)
  
And here's what I see when I launch any of your new versions:
```
Pop-up application window: infekt-win32.exe - Entry Point Not Found : The entry point for the GetDpiForWindow procedure was not found in the USER32.dll DLL.
Pop-up application window: infekt-win64.exe - Entry Point Not Found : The entry point for the GetDpiForWindow procedure was not found in the USER32.dll DLL.
```
Only portableapps did not check.

**Comment by wvxwxvw** [comment]
I saw in the description that Windows 7 is not supported. Only it is not clear why this is an artificial restriction.

**Comment by ask2018** [comment]
I'm not the dev of this software, but I'll try to answer your question, because today I wanted to update Infekt as well and ended with the same error on my Win7 machine.
I guess this has something to do with this in changelog "Windows: first preparations for High DPI (4k displays) support."
The problem is GetDpiForWindow needs at least Windows 10, version 1607
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow
I don't know whats the future plans of using this, but in current version it seems to be used only in the aboutbox (or at least I didn't noticed it elsewhere). So I've just patched that out from the binary and replaced with fixed value for 96DPI and it works again on my Win7 machine.
In my opinion some compatibility mode for older systems would be nice, because there is still lot of people refusing to update to 10, but this is up to the developer of this application.

**Comment by ask2018** [comment]
Quick update on this issue. If you want to run current version of Infekt without any modifications to the code on Win7. You can use this:https://github.com/vxiiduu/VxKex
I've just tested Infekt 1.2.0 Portable on my Win7 x64 system and it works just fine.

**Comment by wvxwxvw** [comment]
@ask2018 
How to link files? Or what does the command line look like?

**Comment by ask2018** [comment]
Just install the VxKex. Then unpack Infekt portable somewhere, right click the exe and go to file attributes (or what's the exact name of it on English system - I'm on my native language one) And there you should see VxKex tab. So go there and enable the first 2 options there in compatibility mode and set it to Win10. It's basically the same as you set compatibility mode for older systems inside Win7 just this has extra new tab there added after you install VxKex.

**Comment by wvxwxvw** [comment]
Gorgeous. Thank you.

**Comment by ask2018** [comment]
Your welcome :)
